# Generated by Django 6.0 on 2026-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="access",
            field=models.CharField(
                choices=[
                    ("granted", "Granted"),
                    ("under_review", "Under_Review"),
                    ("denied", "Denied"),
                ],
                default="granted",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("lead", "Lead"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                ],
                default="admin",
                max_length=15,
            ),
        ),
    ]
