# Generated by Django 6.0 on 2026-01-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="teams.teams",
            ),
        ),
    ]
