# Generated by Django 6.0 on 2026-01-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("quests", "0002_alter_quest_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="organization.organization",
            ),
        ),
    ]
