# Generated by Django 6.0 on 2026-01-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0003_alter_quest_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
    ]
