# Generated by Django 6.0 on 2026-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0004_quest_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In_Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
